// COMMON
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_WHOAMI_SUCCESS = 'AUTH_WHOAMI_SUCCESS';
export const AUTH_REFRESH_SUCCESS = 'AUTH_REFRESH_SUCCESS';
