export const BEGIN_REQUEST_AUTH = 'BEGIN_REQUEST_AUTH';
export const END_REQUEST_AUTH = 'END_REQUEST_AUTH';

export const LOGIN_SUCCESS_AUTH = 'LOGIN_SUCCESS_AUTH';
export const LOGOUT_SUCCESS_AUTH = 'LOGOUT_SUCCESS_AUTH';
export const WHOAMI_SUCCESS_AUTH = 'WHOAMI_SUCCESS_AUTH';
export const REFRESH_SUCCESS_AUTH = 'REFRESH_SUCCESS_AUTH';
