export const HOME_REQUEST = 'HOME_REQUEST';
export const HOME_SUCCESS = 'HOME_SUCCESS';
export const HOME_END = 'HOME_END';

export const HEALTH_CHECK_REQUEST = 'HEALTH_CHECK_REQUEST';
export const HEALTH_CHECK_SUCCESS = 'HEALTH_CHECK_SUCCESS';
export const HEALTH_CHECK_END = 'HEALTH_CHECK_END';
