// COMMON
export const DASH_BOARD_REQUEST = 'DASH_BOARD_REQUEST';
export const DASH_BOARD_FAILURE = 'DASH_BOARD_FAILURE';

export const DASH_BOARD_GET_HOME_SUCCESS = 'DASH_BOARD_GET_HOME_SUCCESS';
export const DASH_BOARD_GET_HEALTH_CHECK_SUCCESS =
  'DASH_BOARD_GET_HEALTH_CHECK_SUCCESS';
