export const HOME_REQUEST = 'HOME_REQUEST';
export const HOME_FAILURE = 'HOME_FAILURE';
export const HOME_SUCCESS = 'HOME_SUCCESS';

export const HEALTH_CHECK_REQUEST = 'HEALTH_CHECK_REQUEST';
export const HEALTH_CHECK_FAILURE = 'HEALTH_CHECK_FAILURE';
export const HEALTH_CHECK_SUCCESS = 'HEALTH_CHECK_SUCCESS';
