// COMMON
export const NOTIFY_REQUEST = 'NOTIFY_REQUEST';
export const NOTIFY_FAILURE = 'NOTIFY_FAILURE';

export const NOTIFY_GET_ALL_SUCCESS = 'NOTIFY_GET_ALL_SUCCESS';
export const NOTIFY_GET_ID_SUCCESS = 'NOTIFY_GET_ID_SUCCESS';

export const SHOW_TOAST_CHANGE_PASSWORD_TEMPORARY_NOTIFY =
  'SHOW_TOAST_CHANGE_PASSWORD_TEMPORARY_NOTIFY';
export const HIDE_TOAST_CHANGE_PASSWORD_TEMPORARY_NOTIFY =
  'HIDE_TOAST_CHANGE_PASSWORD_TEMPORARY_NOTIFY';
