export const CALL_REQUEST_ORGANIZATION = 'CALL_REQUEST_ORGANIZATION';
export const END_REQUEST_ORGANIZATION = 'END_REQUEST_ORGANIZATION';

export const GET_ALL_ORGANIZATION = 'GET_ALL_ORGANIZATION';
export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
export const GET_ID_ORGANIZATION = 'GET_ID_ORGANIZATION';
export const EDIT_ORGANIZATION = 'EDIT_ORGANIZATION';
