// COMMON
export const ORGANIZATION_REQUEST = 'ORGANIZATION_REQUEST';
export const ORGANIZATION_FAILURE = 'ORGANIZATION_FAILURE';
export const ORGANIZATION_RESET_RECORD = 'ORGANIZATION_RESET_RECORD';

export const ORGANIZATION_GET_ALL_SUCCESS = 'ORGANIZATION_GET_ALL_SUCCESS';
export const ORGANIZATION_GET_ID_SUCCESS = 'ORGANIZATION_GET_ID_SUCCESS';
export const ORGANIZATION_CREATE_SUCCESS = 'ORGANIZATION_CREATE_SUCCESS';
export const ORGANIZATION_UPDATE_SUCCESS = 'ORGANIZATION_UPDATE_SUCCESS';
