// COMMON
export const PERMISSION_REQUEST = 'PERMISSION_REQUEST';
export const PERMISSION_FAILURE = 'PERMISSION_FAILURE';
export const PERMISSION_RESET_RECORD = 'PERMISSION_RESET_RECORD';

export const PERMISSION_GET_ALL_SUCCESS = 'PERMISSION_GET_ALL_SUCCESS';
export const PERMISSION_GET_ID_SUCCESS = 'PERMISSION_GET_ID_SUCCESS';
export const PERMISSION_CREATE_SUCCESS = 'PERMISSION_CREATE_SUCCESS';
export const PERMISSION_UPDATE_SUCCESS = 'PERMISSION_UPDATE_SUCCESS';
