export const CALL_REQUEST_PERMISSION = 'CALL_REQUEST_PERMISSION';
export const END_REQUEST_PERMISSION = 'END_REQUEST_PERMISSION';

export const GET_ALL_PERMISSION = 'GET_ALL_PERMISSION';
export const CREATE_PERMISSION = 'CREATE_PERMISSION';
export const GET_ID_PERMISSION = 'GET_ID_PERMISSION';
export const EDIT_PERMISSION = 'EDIT_PERMISSION';
