export const RESET_RECORDS_PROJECT = 'RESET_RECORDS_PROJECT';
export const CALL_REQUEST_PROJECT = 'CALL_REQUEST_PROJECT';
export const END_REQUEST_PROJECT = 'END_REQUEST_PROJECT';

export const GET_ALL_PROJECT = 'GET_ALL_PROJECT';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const GET_ID_PROJECT = 'GET_ID_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
