// COMMON
export const PROJECT_REQUEST = 'PROJECT_REQUEST';
export const PROJECT_FAILURE = 'PROJECT_FAILURE';
export const PROJECT_RESET_RECORD = 'PROJECT_RESET_RECORD';

export const PROJECT_GET_ALL_SUCCESS = 'PROJECT_GET_ALL_SUCCESS';
export const PROJECT_GET_ID_SUCCESS = 'PROJECT_GET_ID_SUCCESS';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';
