export const CALL_REQUEST_ROLE = 'CALL_REQUEST_ROLE';
export const END_REQUEST_ROLE = 'END_REQUEST_ROLE';

export const GET_ALL_ROLE = 'GET_ALL_ROLE';
export const CREATE_ROLE = 'CREATE_ROLE';
export const GET_ID_ROLE = 'GET_ID_ROLE';
export const EDIT_ROLE = 'EDIT_ROLE';
export const GET_ALL_USER_IN_ROLE = 'GET_ALL_USER_IN_ROLE';
export const GET_ALL_PERMISSION_IN_ROLE = 'GET_ALL_PERMISSION_IN_ROLE';
