// COMMON
export const ROLE_REQUEST = 'ROLE_REQUEST';
export const ROLE_FAILURE = 'ROLE_FAILURE';
export const ROLE_RESET_RECORD = 'ROLE_RESET_RECORD';

export const ROLE_GET_ALL_SUCCESS = 'ROLE_GET_ALL_SUCCESS';
export const ROLE_GET_ID_SUCCESS = 'ROLE_GET_ID_SUCCESS';
export const ROLE_CREATE_SUCCESS = 'ROLE_CREATE_SUCCESS';
export const ROLE_UPDATE_SUCCESS = 'ROLE_UPDATE_SUCCESS';
export const ROLE_GET_ALL_USER_SUCCESS = 'ROLE_GET_ALL_USER_SUCCESS';
export const ROLE_GET_ALL_PERMISSION_SUCCESS =
  'ROLE_GET_ALL_PERMISSION_SUCCESS';
