// COMMON
export const TEAM_REQUEST = 'TEAM_REQUEST';
export const TEAM_FAILURE = 'TEAM_FAILURE';
export const TEAM_RESET_RECORD = 'TEAM_RESET_RECORD';

export const TEAM_GET_ALL_SUCCESS = 'TEAM_GET_ALL_SUCCESS';
export const TEAM_GET_ID_SUCCESS = 'TEAM_GET_ID_SUCCESS';
export const TEAM_CREATE_SUCCESS = 'TEAM_CREATE_SUCCESS';
export const TEAM_UPDATE_SUCCESS = 'TEAM_UPDATE_SUCCESS';
export const TEAM_GET_ALL_MEMBER_IN_TEAM_SUCCESS =
  'TEAM_GET_ALL_MEMBER_IN_TEAM_SUCCESS';
export const TEAM_GET_ALL_MEMBER_NOT_ON_TEAM_SUCCESS =
  'TEAM_GET_ALL_MEMBER_NOT_ON_TEAM_SUCCESS';
