// COMMON
export const USER_REQUEST = 'USER_REQUEST';
export const USER_FAILURE = 'USER_FAILURE';
export const USER_RESET_RECORD = 'USER_RESET_RECORD';

export const USER_GET_ALL_SUCCESS = 'USER_GET_ALL_SUCCESS';
export const USER_GET_ID_SUCCESS = 'USER_GET_ID_SUCCESS';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
